### ISSUE TITLE
ST3

### ISSUE THREAD

**Issue by FichteFoll** [travmik/ZenTabs#1]
This is mostly FYI.

From taking a quick look at this it _should_ be really easy to add support for ST3. Just change:

``` py
g_setting = sublime.load_settings('zentabs.sublime-settings')

g_tabLimit = g_setting.get('open_tab_limit', 10)
```

to:

``` py
g_tabLimit = 10
def plugin_loaded():
    global g_tabLimit
    settings = sublime.load_settings('zentabs.sublime-settings')
    g_tabLimit = settings.get('open_tab_limit', g_tabLimit)
```

and add parens aroung your `print` statements in `printStat()`

However, `on_activated` will likely be fired before `plugin_loaded` was called so I set the default value to `10`. That's undesirable if you set the value to something >10 because restarting ST will then probably result in all tabs more than 10 being closed.

---

Other FYI things I didn't consider to be worth their own issues:
- You are only using one setting, yet you require the setting to be specified in a separate `zentabs.sublime-settings` file. Instead, you should try using the general preferences here and add a prefix to your setting name, e.g. `"zentabs.open_tab_limit"`.
- In line [36 and 37](https://github.com/travmik/ZenTabs/blob/master/ZenTabs.py#L36) you use two long list comprehensions. If you just used a normal `for view in sublime.active_window().views(): #...` it would drastically reduce code complexity and increase performance because you can do both in one loop.

**Comment by travmik** [comment]
Thank you. I will look. 

Python is not mine primary language so your comment is very useful for me. 

I appreciate that.

**Comment by travmik** [comment]
1. Parens to print added
2. plugin_loaded method added BUT on ST2 it is never called and I call it when window activated - thinking about how to do right now.
3. What is wrong with using separate settings file for plug? The more I have some plans for new features and they will need also some settings. I haven't a lot experience with plugins for ST may be you could explane it.
4. Am I right understand that you think that instead of using two list comprehensions I can use one "foreach" and fill two lists?

thanks

**Comment by FichteFoll** [comment]
2) Add this at the end of the file:

``` py
if int(sublime.version()) < 3000:
    plugin_loaded()
```

3) If you really plan on adding more funtionality, that's fine. But _I_ personally dislike having 16 `anything.sublime-settings` in my User package, one for each plugin, while most of them only contain 1-4 lines.

4) Yes.

**Comment by travmik** [comment]
2 - that is what I need.=)
3 - you right. I will think about it.
4 - this function called only when you are switching between ST windows. I think with comprehensions approach code is more readable. But also added it to todo.

thank you.

**Comment by FichteFoll** [comment]
Here is what I thought of:

``` py
def on_activated(self, view):
    if sublime.active_window().id() != self.window_id:
        self.opened_tab_ids = [view.id() for view in sublime.active_window().views() if not view.is_dirty() and not view.is_scratch()]
        self.edited_tab_ids = [view.id() for view in sublime.active_window().views() if view.is_dirty() or view.is_scratch()]
        self.window_id = sublime.active_window().id()
    sublime.set_timeout(lambda: self.process(view.id()), 200)
```

``` py
def on_activated(self, view):
    if sublime.active_window().id() != self.window_id:
        self.window_id = sublime.active_window().id()

        self.opened_tab_ids, self.edited_tab_ids = [], []
        for view in sublime.active_window().views():
            if not view.is_dirty() and not view.is_scratch():
                self.opened_tab_ids.append(view.id())
            if view.is_dirty() and view.is_scratch():
                self.edited_tab_ids.append(view.id())

    sublime.set_timeout(lambda: self.process(view.id()), 200)
```

Of course, if you like the first one more, you are more than free to do so. I just dislike having long list comprehensions (on a single line).

**Comment by travmik** [comment]
thank you. 

resolved
