### ISSUE TITLE
Does not display newly opened tab

### ISSUE THREAD

**Issue by rtkbkish** [travmik/ZenTabs#10]
If open_tab_limit number of tabs are opened, then after opening a new tab (say by selecting a file from the sidebar), the display will be often be left on a seemingly random tab. This is very annoying.

**Comment by travmik** [comment]
Sorry, just to be on the same page. You say about situation when you open open_tab_limit+1 tab and you see like one of tabs in tabbar blinking for a second. Am I right? Is this a problem?

**Comment by rtkbkish** [comment]
I am using build 3053. When I double-click on a file from the sidebar, it opens and displays briefly, then another tab is closed, and finally the view is left displaying a _different_ tab than the one I just opened. I have to actually explicitly switch to the tab that I wanted. This happens very consistently.

**Comment by travmik** [comment]
New version will be in Package Control after one hour I believe. 
Sorry for inconvenience - I am using ST2 and physically can't make full test on both platforms)  

it's time for me to upgrade to ST3 I think =)
