### ISSUE TITLE
New tab is not activated when opened

### ISSUE THREAD

**Issue by kedder** [travmik/ZenTabs#14]
Sometimes when opening new file, new tab for it is opened, but focus is left on old tab, so I have to switch to new tab manually. I use ST3.

Steps to reproduce:
1. Open enough files for Zen Tabs to start closing old ones
2. Use `Ctrl+Shift+R` to find symbol, not defined in one of open files
3. Press Enter to open it

What I observe: one of the old tabs is closed, new tab is opened in background, but focus is switched back to the tab, where I was when I pressed `Ctrl+Shift+R`.

What I expect to happen: one of the old tabs is closed, newly opened tab becomes active. 

This also happens when I use CTags to jump to a symbol. It seems that it happens when new file is opened without "previewing" it first (but I'm not sure if that's a real reason or just coincidence)

**Comment by thecotne** [comment]
this bug is also appears when opening file from desktop not only with "find symbol in project"
