### ISSUE TITLE
Tab Numbering

### ISSUE THREAD

**Issue by fascox** [travmik/ZenTabs#16]
don't know if it's already configurable in SublimeText by would be nice to show the tab number before the filename as an indication for  tab switch (cmd+n)

**Comment by travmik** [comment]
Yes - it would be useful. But I think it is impossible for now.

**Comment by FichteFoll** [comment]
``` py
import os; list(v.set_name("%d %s" % (i + 1, os.path.basename(v.file_name() or ""))) for i, v in enumerate(window.views()))
```

Sadly this essentially renames the files and thus makes ST mark them as "unsaved" as well because the newly named files don't exist on HDD.
