### ISSUE TITLE
Unable to save settings

### ISSUE THREAD

**Issue by leeahoward** [travmik/ZenTabs#2]
When installed using package manager it was installed in "Zen Tabs" instead of "ZenTabs".  The space in the folder name caused an issue where I could not save the settings file.   When I noticed the issue I renamed the folder removing the space and it seemed to fix the issue.

**Comment by travmik** [comment]
thank you. I know about this bug. 
It fixed already and will be in git today.

**Comment by travmik** [comment]
fixed
