### ISSUE TITLE
Is ZenTabs still under active development?

### ISSUE THREAD

**Issue by philippotto** [travmik/ZenTabs#24]
I currently have some issues with ZenTabs and would like to contribute. But after having seen that one pull request and several issues are still open for some time, I would like to ensure that my work will not be in vain. So, what is the status here?
@travmik, if you don't have time on your hands, maybe you could grant some willing contributors access rights for this repository?

**Comment by travmik** [comment]
@philippotto Hey man. I’m sorry for late response - was on business trip and didn’t check github at all.
Yes I will be very appreciate for contributions. Now unfortunately have no time to finish my full refactoring. Will push it to separate branch - may be it will help.

**Comment by philippotto** [comment]
I'm glad to hear that :)
