### ISSUE TITLE
Auto closing not working

### ISSUE THREAD

**Issue by mupkoo** [travmik/ZenTabs#8]
Hello,

I am running Mac OSX Lion 10.7.5 with Sublime Text Build 3047.
I installed ZenTabs through the package control (even received an updated today).

I am still with the default settings:

```
{
    "open_tab_limit":  10,
    "highlight_modified_tabs": true,
    "show_full_path": false
} 
```

but I can open more than 10 tabs and I don't see the highlighting.

Thank you

**Comment by travmik** [comment]
It is the shame =)

Wrong settings file name. By default I set limit to 50 ((

Fixed - new version will be available within half hour.

**Comment by travmik** [comment]
@mupkoo please verify.

**Comment by mupkoo** [comment]
Hello travmik

Now the closing feature works. :+1: 
Great idea btw and thank you :)

**Comment by travmik** [comment]
good! :sunglasses:

**Comment by zalew16** [comment]
On issue
