### ISSUE TITLE
Error loading colour scheme.... - /Monokai.tmTheme Sublime 2

### ISSUE THREAD

**Issue by gwindes** [travmik/ZenTabs#9]
Recently installed the plugin and when I restarted my sublime (2) I got a popup error with `Error loading colour scheme Packages/Color Scheme - /Monokai.tmTheme:
 Error parsing plist xml: Failed to open file In file "Packages/Color Scheme - /Monokai.tmTheme"`

It seems to be overwriting my `Preferences.sublime-settings` file and removing the previous content of:
`{
  "color_scheme": "Packages/Color Scheme - Default/Monokai.tmTheme",
  "font_size": 11,
  "highlight_modified_tabs": true,
  "ignored_packages":  ["Vintage"]
}`

with just
`{"highlight_modified_tabs": true}`

It seems to still work fine on my other machine that has SublimeText 3 installed. In order to fix my color scheme in SublimeText 2 I have to uninstall the plugin and reassign my color scheme. Resetting the color scheme does not work will the plugin is still installed. 

Note: I do use dropbox syncing for cross machine preference sharing as described here: https://sublime.wbond.net/docs/syncing

This error is happening on a Win 7, 64bit machine.

Love the plugin! Let me know if there is any more info you need. 

![image](https://f.cloud.github.com/assets/843453/1182872/e1160970-2223-11e3-8c5c-0f2964bf3a28.png)

**Comment by travmik** [comment]
Thank you for your submit. I will check it now and fix ASAP. 

Will be in touch.

**Comment by travmik** [comment]
Seems like I fixed it. Looks like Zen Tabs loaded earlier than preferences and rewriting all values. 
Now I set value with timeout =)
Please verify it after one hour - when release will be available in Package Control. 

Sorry for you preferences ;)

**Comment by gwindes** [comment]
> Sorry for you preferences ;)

No worries, they were backed up :)

Just tested again on both Sublime 2 and Sublime 3 and works great!
Thanks for the fix!
